backend:
  name: github
  repo: laiho66/va-comics.com
  branch: main
  base_url: https://va-auth.besleaga-valentin.workers.dev
  client_id: Ov23liRXBQxQAnqWzvXx # ID-ul tău confirmat

publish_mode: editorial_workflow

media_folder: "assets"
public_folder: "/assets"

collections:
  # 1. COLECȚIA DE CRONICI
  - name: "chronicles"
    label: "Chronicles"
    folder: "content/chronicles"
    create: true
    delete: true # Permite ștergerea/unpublish la cronici
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      
      # --- CLASIFICARE PRIN CATEGORII ---
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["Reviews", "News", "Interviews", "Theories", "Chronicles"]
        default: "Cronici"

      - label: "Linked Volume"
        name: "linked_volume"
        widget: "relation"
        collection: "volumes"
        search_fields: ["title"]
        value_field: "url"
        display_fields: ["title"]
        required: false

      - {label: "Log Content", name: "body", widget: "markdown"}
      - {label: "Log Content", name: "body", widget: "markdown", minimal: true}

  # 2. COLECȚIA DE VOLUME
  - name: "volumes"
    label: "Volumes Library"
    delete: true # Permite ștergerea/unpublish la volume
    editor:
      preview: false
    files:
      - label: "Dead Drop: Volume 1"
        name: "vol1"
        file: "content/volumes/vol1.md"
        fields:
          - {label: "Title", name: "title", widget: "string", default: "Volume 1"}
          - {label: "URL", name: "url", widget: "string", default: "deaddrop/vol1.html"}
      - label: "Dead Drop: Volume 2"
        name: "vol2"
        file: "content/volumes/vol2.md"
        fields:
          - {label: "Title", name: "title", widget: "string", default: "Volume 2"}
          - {label: "URL", name: "url", widget: "string", default: "deaddrop/vol2.html"}
